markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Zach Holman
url: http://zachholman.com
description: A fantastic blog that is fantastic.
twitter: holman
